# This is a basic workflow to help you get started with Actions

name: Create Archive
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.0
      with:
        type: 'zip'
        filename: 'pack.zip'
        exclusions: '*.md* /*index.html*'
