name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      commit: ${{ github.sha }}
      commitmsg: ${{ github.event.head_commit.message }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'pack.zip'
        exclusions: '*.md* /*index.html*/*.git*/*.github*'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "pack.zip"
        tag: rp-${{ env.commit }}
        name: ${{ env.commit }}
        token: ${{ secrets.GITHUB_TOKEN }}